### ISSUE TITLE
Extractor vs. ffmpeg

### ISSUE THREAD

**Issue by neilyoung** [slhck/h26x-extractor#6]
Hi,

I'm wondering if the extractor would be able to point out errors. I'm having a stream, which is extracted w/o visible complains, but both - ffplay and ffprobe - complain like so:

[h264 @ 0x7ff926819000] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x7ff926819000] decode_slice_header error
[h264 @ 0x7ff926819000] no frame!

even though the video is presented (ffplay). Any idea, what they might have problems with?

**Comment by neilyoung** [comment]
No offence, but IMO using a tool like this is more suggested:

`ffmpeg -i video.h264 -c copy -bsf:v trace_headers -f null - 2> NALUS.txt`

**Comment by slhck** [comment]
The particular filter you mention (`trace_headers`) was only created a few weeks before I published this tool (which had been an internal tool for some time before that).

So, feel free to use ffmpeg if you want to! You are not forced to use `h26x-extractor`.

**Comment by neilyoung** [comment]
Thanks. As said: No offence :)

**Comment by slhck** [comment]
Sure! Thanks for reminding me of that filter. I will add it to the README as an alternative.

**Comment by neilyoung** [comment]
It’s blazing fast but shows some weird things I don’t get
